import "./globals.css";
import { Quicksand, Bungee } from "next/font/google";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: ["300", "400", "500"],
  display: "swap",
});

const bungee = Bungee({
  subsets: ["latin"],
  variable: "--font-bungee",
  weight: ['400'],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${bungee.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
